name: CI
on:
  push:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: echo interrepo-actions-dst OK
      - run: |
          echo Always fails
          exit 1
